http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  api:
      host: 'localhost'
      paths: '/ip'
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
policies:
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt-auth
  - basic-auth
  - session-auth
  - local-auth
  - auth-secure
pipelines:
  default:
    apiEndpoints:
      - api
    policies: 
      - auth-secure:
      - jwt-auth:          
      - proxy: # policy name
          -    # array of objects with condition\action properties
            action:
              serviceEndpoint: httpbin # see declaration above
